// <auto-generated />
using System;
using BlogApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlogApp.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230317124111_UpdatedComment")]
    partial class UpdatedComment
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BlogApp.Core.Entities.Concrete.About", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("About");
                });

            modelBuilder.Entity("BlogApp.Core.Entities.Concrete.Blog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CommentCount")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<string>("CreatedByUsername")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("LikeCount")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UpdatedByUsername")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("ViewCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Blogs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CommentCount = 0,
                            Content = "Son yıllarda teknoloji hızla gelişiyor ve bu gelişmelerle birlikte veri bilimi ve makine öğrenmesi alanları da hızla büyüyor. Ancak, bu terimlerin ne anlama geldiği konusunda hala birçok insan kafa karışıklığı yaşayabilir. Bu yazıda, veri bilimi ve makine öğrenmesi hakkında genel bir bilgi vereceğim ve bunların neden önemli olduğunu anlatacağım.\r\n\r\nVeri bilimi, verilerin analiz edilmesi, yorumlanması ve anlamlı sonuçlar elde edilmesi için istatistik, matematik ve bilgisayar bilimlerinin kullanıldığı bir alandır. Veri bilimciler, verileri toplar, temizler, işler ve model oluştururlar. Bu modeller, öngörülebilir sonuçlar elde etmek için kullanılabilir.\r\n\r\nMakine öğrenmesi ise, bilgisayarların belirli bir görevi yerine getirmek için verileri kullanarak kendi kendine öğrenmesi ve geliştirmesi anlamına gelir. Bu yöntem, birçok alanda kullanılabilir. Örneğin, e-posta spam filtrelemesi, resim tanıma, doğal dil işleme ve daha birçok şey.\r\n\r\nNeden Veri Bilimi ve Makine Öğrenmesi Önemlidir?\r\n\r\nVeri bilimi ve makine öğrenmesi, işletmeler, hükümetler ve toplumlar için önemli bir rol oynamaktadır. Bu alanlar, daha iyi kararlar almak ve verimliliklerini artırmak için büyük miktarda veriyi analiz etmek zorundadır. Veri bilimi ve makine öğrenmesi, bu verilerin anlamlı hale getirilmesine yardımcı olabilir.\r\n\r\nÖrneğin, bir perakende şirketi, müşteri davranışları hakkında daha iyi bir anlayışa sahip olduğunda, daha iyi bir müşteri deneyimi sunabilir ve daha etkili bir pazarlama stratejisi oluşturabilir. Bir sağlık hizmetleri şirketi, büyük veri analizi kullanarak hastalıkların yayılmasını tahmin edebilir ve sağlık hizmetlerinin daha iyi bir şekilde yönetilmesine yardımcı olabilir.\r\n\r\nSonuç olarak, veri bilimi ve makine öğrenmesi, birçok alanda büyük önem taşıyan güçlü araçlardır. Bu alanların hızla gelişmesi, daha iyi kararlar almak ve verimliliği artırmak için daha fazla veriyi analiz etmemizi sağlayacaktır.",
                            CreatedByUsername = "ozkky",
                            CreatedDate = new DateTime(2023, 3, 17, 15, 41, 10, 17, DateTimeKind.Local).AddTicks(6547),
                            ImageUrl = "postImages/defaultImage.png",
                            IsActive = true,
                            IsDeleted = false,
                            LikeCount = 100,
                            Title = "Veri Bilimi ve Makine Öğrenmesi: Geleceğin Teknolojisi",
                            UpdatedByUsername = "ozkky",
                            UpdatedDate = new DateTime(2023, 3, 17, 15, 41, 10, 17, DateTimeKind.Local).AddTicks(6555),
                            UserId = 1,
                            ViewCount = 100
                        },
                        new
                        {
                            Id = 2,
                            CommentCount = 0,
                            Content = "Günümüzde teknolojinin hızlı gelişimiyle birlikte siber güvenlik tehditleri de artış göstermiştir. Siber suçlular, bireysel ve kurumsal kullanıcıların bilgi güvenliğini tehdit ederek, zararlı yazılımlar, kimlik avı saldırıları, DDoS saldırıları ve daha birçok yöntemle hedeflerine ulaşmaya çalışmaktadırlar. Bu nedenle siber güvenlik, günümüzde hayati bir öneme sahip bir konudur.\r\n\r\nSiber güvenlik tehditleri, bireysel kullanıcıların yanı sıra, işletmeler ve kurumlar için de büyük bir risk oluşturur. Siber saldırılara maruz kalan şirketler, müşteri güvenini kaybedebilir, maddi zararlarla karşılaşabilir ve hatta itibar kaybına uğrayabilirler. Bu nedenle, kurumlar siber güvenliği ciddiye almalı ve koruma önlemleri almalıdırlar.\r\n\r\nSiber güvenliği sağlamak için izlenebilecek birkaç yöntem şöyle sıralanabilir:\r\n\r\nGüçlü Parolalar Kullanın: Parolalar, çevrimiçi güvenliğiniz için ilk savunma hattıdır. Güçlü bir parola, saldırganların şifrenizi tahmin etmelerini önleyerek hesabınızın güvenliğini artırır. Şifrenizde büyük/küçük harfler, sayılar ve semboller kullanarak daha güçlü bir parola oluşturabilirsiniz.\r\n\r\nGüncel Yazılımlar Kullanın: Yazılım güncellemeleri, bilgisayarınızdaki güvenlik açıklarını kapatır. Bu nedenle, bilgisayarınızda kullandığınız yazılımları ve işletim sistemini güncel tutmanız, siber güvenliğiniz için çok önemlidir.\r\n\r\nKimlik Doğrulama Yöntemleri Kullanın: İki faktörlü kimlik doğrulama, parola ile birlikte bir başka doğrulama yöntemi daha kullanarak hesabınızın güvenliğini artırır. Bu sayede, saldırganların hesabınıza erişmelerini zorlaştırarak güvenliğinizi artırabilirsiniz.\r\n\r\nVeri Yedeklemesi Yapın: Yedekleme, olası bir saldırı veya sistem hatası durumunda verilerinizin korunmasını sağlar. Verilerinizi yedekleyerek, saldırı sonrası verilerinizi geri yükleyerek kayıplarınızı en aza indirebilirsiniz.",
                            CreatedByUsername = "ozkky",
                            CreatedDate = new DateTime(2023, 3, 17, 15, 41, 10, 17, DateTimeKind.Local).AddTicks(6563),
                            ImageUrl = "postImages/defaultImage.png",
                            IsActive = true,
                            IsDeleted = false,
                            LikeCount = 123,
                            Title = "Siber Güvenlik Tehditleri ve Önleme Yöntemleri",
                            UpdatedByUsername = "ozkky",
                            UpdatedDate = new DateTime(2023, 3, 17, 15, 41, 10, 17, DateTimeKind.Local).AddTicks(6564),
                            UserId = 1,
                            ViewCount = 243
                        },
                        new
                        {
                            Id = 3,
                            CommentCount = 0,
                            Content = "Günümüzde teknolojinin hızlı gelişimiyle birlikte siber güvenlik tehditleri de artış göstermiştir. Siber suçlular, bireysel ve kurumsal kullanıcıların bilgi güvenliğini tehdit ederek, zararlı yazılımlar, kimlik avı saldırıları, DDoS saldırıları ve daha birçok yöntemle hedeflerine ulaşmaya çalışmaktadırlar. Bu nedenle siber güvenlik, günümüzde hayati bir öneme sahip bir konudur.\r\n\r\nSiber güvenlik tehditleri, bireysel kullanıcıların yanı sıra, işletmeler ve kurumlar için de büyük bir risk oluşturur. Siber saldırılara maruz kalan şirketler, müşteri güvenini kaybedebilir, maddi zararlarla karşılaşabilir ve hatta itibar kaybına uğrayabilirler. Bu nedenle, kurumlar siber güvenliği ciddiye almalı ve koruma önlemleri almalıdırlar.\r\n\r\nSiber güvenliği sağlamak için izlenebilecek birkaç yöntem şöyle sıralanabilir:\r\n\r\nGüçlü Parolalar Kullanın: Parolalar, çevrimiçi güvenliğiniz için ilk savunma hattıdır. Güçlü bir parola, saldırganların şifrenizi tahmin etmelerini önleyerek hesabınızın güvenliğini artırır. Şifrenizde büyük/küçük harfler, sayılar ve semboller kullanarak daha güçlü bir parola oluşturabilirsiniz.\r\n\r\nGüncel Yazılımlar Kullanın: Yazılım güncellemeleri, bilgisayarınızdaki güvenlik açıklarını kapatır. Bu nedenle, bilgisayarınızda kullandığınız yazılımları ve işletim sistemini güncel tutmanız, siber güvenliğiniz için çok önemlidir.\r\n\r\nKimlik Doğrulama Yöntemleri Kullanın: İki faktörlü kimlik doğrulama, parola ile birlikte bir başka doğrulama yöntemi daha kullanarak hesabınızın güvenliğini artırır. Bu sayede, saldırganların hesabınıza erişmelerini zorlaştırarak güvenliğinizi artırabilirsiniz.\r\n\r\nVeri Yedeklemesi Yapın: Yedekleme, olası bir saldırı veya sistem hatası durumunda verilerinizin korunmasını sağlar. Verilerinizi yedekleyerek, saldırı sonrası verilerinizi geri yükleyerek kayıplarınızı en aza indirebilirsiniz.",
                            CreatedByUsername = "adminuser",
                            CreatedDate = new DateTime(2023, 3, 17, 15, 41, 10, 17, DateTimeKind.Local).AddTicks(6569),
                            ImageUrl = "postImages/defaultImage.png",
                            IsActive = true,
                            IsDeleted = false,
                            LikeCount = 134,
                            Title = "Yapay Zeka ve Otomasyon",
                            UpdatedByUsername = "adminuser",
                            UpdatedDate = new DateTime(2023, 3, 17, 15, 41, 10, 17, DateTimeKind.Local).AddTicks(6570),
                            UserId = 2,
                            ViewCount = 222
                        },
                        new
                        {
                            Id = 4,
                            CommentCount = 0,
                            Content = "Günümüzde teknolojinin hızlı gelişimiyle birlikte siber güvenlik tehditleri de artış göstermiştir. Siber suçlular, bireysel ve kurumsal kullanıcıların bilgi güvenliğini tehdit ederek, zararlı yazılımlar, kimlik avı saldırıları, DDoS saldırıları ve daha birçok yöntemle hedeflerine ulaşmaya çalışmaktadırlar. Bu nedenle siber güvenlik, günümüzde hayati bir öneme sahip bir konudur.\r\n\r\nSiber güvenlik tehditleri, bireysel kullanıcıların yanı sıra, işletmeler ve kurumlar için de büyük bir risk oluşturur. Siber saldırılara maruz kalan şirketler, müşteri güvenini kaybedebilir, maddi zararlarla karşılaşabilir ve hatta itibar kaybına uğrayabilirler. Bu nedenle, kurumlar siber güvenliği ciddiye almalı ve koruma önlemleri almalıdırlar.\r\n\r\nSiber güvenliği sağlamak için izlenebilecek birkaç yöntem şöyle sıralanabilir:\r\n\r\nGüçlü Parolalar Kullanın: Parolalar, çevrimiçi güvenliğiniz için ilk savunma hattıdır. Güçlü bir parola, saldırganların şifrenizi tahmin etmelerini önleyerek hesabınızın güvenliğini artırır. Şifrenizde büyük/küçük harfler, sayılar ve semboller kullanarak daha güçlü bir parola oluşturabilirsiniz.\r\n\r\nGüncel Yazılımlar Kullanın: Yazılım güncellemeleri, bilgisayarınızdaki güvenlik açıklarını kapatır. Bu nedenle, bilgisayarınızda kullandığınız yazılımları ve işletim sistemini güncel tutmanız, siber güvenliğiniz için çok önemlidir.\r\n\r\nKimlik Doğrulama Yöntemleri Kullanın: İki faktörlü kimlik doğrulama, parola ile birlikte bir başka doğrulama yöntemi daha kullanarak hesabınızın güvenliğini artırır. Bu sayede, saldırganların hesabınıza erişmelerini zorlaştırarak güvenliğinizi artırabilirsiniz.\r\n\r\nVeri Yedeklemesi Yapın: Yedekleme, olası bir saldırı veya sistem hatası durumunda verilerinizin korunmasını sağlar. Verilerinizi yedekleyerek, saldırı sonrası verilerinizi geri yükleyerek kayıplarınızı en aza indirebilirsiniz.",
                            CreatedByUsername = "editoruser",
                            CreatedDate = new DateTime(2023, 3, 17, 15, 41, 10, 17, DateTimeKind.Local).AddTicks(6575),
                            ImageUrl = "postImages/defaultImage.png",
                            IsActive = true,
                            IsDeleted = false,
                            LikeCount = 233,
                            Title = "İnovasyon ve Yenilik",
                            UpdatedByUsername = "editoruser",
                            UpdatedDate = new DateTime(2023, 3, 17, 15, 41, 10, 17, DateTimeKind.Local).AddTicks(6576),
                            UserId = 4,
                            ViewCount = 2323
                        },
                        new
                        {
                            Id = 5,
                            CommentCount = 0,
                            Content = "Günümüzde evde geçirdiğimiz zamanın artması, iç mekan dekorasyonuna olan ilgiyi arttırdı. İç mekan dekorasyonu sadece evin güzel görünmesini sağlamakla kalmaz, aynı zamanda ruh halimizi ve genel sağlığımızı da etkileyebilir. Doğru renkler, aydınlatma, mobilyalar ve aksesuarlar, evinizi sıcak, rahat ve davetkar bir yer haline getirebilir.\r\n\r\nEvde kalmanın keyfini çıkarmak için, iç mekan dekorasyonunda kişisel tarzınıza uygun seçimler yapabilirsiniz. Minimalist bir tarz mı tercih ediyorsunuz yoksa renkli ve canlı bir dekor mu istiyorsunuz? Evinizdeki doğal ışığı artırmak için hangi renkler ve perdeleri tercih etmelisiniz? Tüm bu soruların yanıtlarını, evde kalmak süresince kendinize daha uygun bir yaşam alanı yaratmak için kullanabilirsiniz.\r\n\r\nUnutmayın, eviniz sizin kişisel alanınızdır ve onun size iyi hissettirmesi önemlidir. Bu nedenle, iç mekan dekorasyonunda kendi stilinizi ve kişiliğinizi yansıtan seçimler yaparak evde kalmanın keyfini çıkarabilirsiniz.",
                            CreatedByUsername = "editoruser",
                            CreatedDate = new DateTime(2023, 3, 17, 15, 41, 10, 17, DateTimeKind.Local).AddTicks(6581),
                            ImageUrl = "postImages/defaultImage.png",
                            IsActive = true,
                            IsDeleted = false,
                            LikeCount = 2113,
                            Title = "Evde Kalmanın Keyfini Çıkarma: İç Mekan Dekorasyon Fikirleri",
                            UpdatedByUsername = "editoruser",
                            UpdatedDate = new DateTime(2023, 3, 17, 15, 41, 10, 17, DateTimeKind.Local).AddTicks(6582),
                            UserId = 4,
                            ViewCount = 2333
                        },
                        new
                        {
                            Id = 6,
                            CommentCount = 0,
                            Content = "Sağlıklı beslenmek, vücudumuzun ihtiyacı olan besinleri alarak sağlıklı bir yaşam sürdürmek için önemlidir. Günümüzde fast food ve işlenmiş gıdaların tüketimi arttıkça, vitamin ve mineral eksikliği gibi sağlık sorunları da artmaktadır. Vitaminler ve mineraller, vücudumuzun doğru bir şekilde çalışması için gerekli olan besin öğeleridir. Bu besinler, kemiklerin güçlendirilmesi, bağışıklık sisteminin korunması ve enerji üretimi gibi birçok vücut fonksiyonu için gereklidir.\r\n\r\nSağlıklı bir beslenme planı, yeterli miktarda vitamin ve mineral alımını içerir. C vitamini, demir, kalsiyum, magnezyum ve potasyum gibi vitamin ve mineraller, günlük diyetimizde yer alması gereken önemli besin öğeleridir. Meyve, sebze, tam tahıllı gıdalar, kuruyemişler ve tohumlar, bu besinlerin en iyi kaynaklarıdır.\r\n\r\nSağlıklı bir beslenme tarzını benimsemek, sadece fiziksel sağlığımız için değil, aynı zamanda mental sağlığımız ve yaşam kalitemiz için de önemlidir. Düzenli egzersizle birlikte sağlıklı beslenme, stres azaltmaya, zihinsel netliği artırmaya ve genel olarak daha mutlu bir yaşam sürdürmeye yardımcı olabilir.\r\n\r\nSonuç olarak, sağlıklı beslenme alışkanlıkları benimsemek, vücudumuzun ihtiyacı olan vitamin ve mineralleri alarak sağlıklı bir yaşam sürdürmek için kritik bir adımdır. Sağlıklı bir diyet, düzenli egzersiz ve yaşam tarzı değişiklikleri, sağlıklı yaşamın anahtarıdır.",
                            CreatedByUsername = "editoruser",
                            CreatedDate = new DateTime(2023, 3, 17, 15, 41, 10, 17, DateTimeKind.Local).AddTicks(6587),
                            ImageUrl = "postImages/defaultImage.png",
                            IsActive = true,
                            IsDeleted = false,
                            LikeCount = 1223,
                            Title = "Sağlıklı Beslenmenin Önemi: Vitamin ve Minerallerin Günlük Hayatta Rolü",
                            UpdatedByUsername = "editoruser",
                            UpdatedDate = new DateTime(2023, 3, 17, 15, 41, 10, 17, DateTimeKind.Local).AddTicks(6588),
                            UserId = 4,
                            ViewCount = 3323
                        },
                        new
                        {
                            Id = 7,
                            CommentCount = 0,
                            Content = "Teknolojinin gelişmesiyle birlikte, dijital dünya ve sosyal medya hayatımızda önemli bir rol oynamaya başladı. İnternet ve sosyal medya platformları, insanlar arasındaki iletişim ve etkileşimi kolaylaştırırken, aynı zamanda yeni sorunlar ve endişeler de yaratıyor.\r\n\r\nSosyal medya, insanların arkadaşlarıyla ve aileleriyle bağlantıda kalmalarına ve dünyadaki olaylar hakkında bilgi edinmelerine yardımcı olurken, zaman zaman da zararlı etkileri olabilir. Sosyal medya kullanımı, özellikle gençler arasında, düşük özgüven, yalnızlık, kaygı ve depresyon gibi ruh sağlığı sorunlarına neden olabilir.\r\n\r\nAyrıca, sosyal medya ve dijital dünya, özellikle çocuklar ve gençler arasında, aşırı tüketim, sosyal medya bağımlılığı, internet güvenliği konularında ciddi endişelere neden oluyor. Dolayısıyla, sosyal medya ve dijital dünya ile ilgili farkındalık yaratmak, bilinçli bir şekilde kullanımını sağlamak için önemlidir.\r\n\r\nSonuç olarak, dijital dünya ve sosyal medya, hayatımızda önemli bir rol oynamaya devam edecek. Bu nedenle, insanlar olarak bu platformları nasıl kullanacağımızı öğrenmeliyiz ve özellikle gençler arasında, sorumlu ve bilinçli bir şekilde kullanımını sağlamalıyız. Sosyal medya ve dijital dünya, hayatımızın bir parçası olsa da, sağlıklı bir denge oluşturmak önemlidir.",
                            CreatedByUsername = "editoruser",
                            CreatedDate = new DateTime(2023, 3, 17, 15, 41, 10, 17, DateTimeKind.Local).AddTicks(6593),
                            ImageUrl = "postImages/defaultImage.png",
                            IsActive = true,
                            IsDeleted = false,
                            LikeCount = 123,
                            Title = "Dijital Dünya ve Sosyal Medyanın Hayatımıza Etkisi",
                            UpdatedByUsername = "editoruser",
                            UpdatedDate = new DateTime(2023, 3, 17, 15, 41, 10, 17, DateTimeKind.Local).AddTicks(6594),
                            UserId = 4,
                            ViewCount = 1223
                        },
                        new
                        {
                            Id = 8,
                            CommentCount = 0,
                            Content = "Düzenli egzersiz yapmak, sağlıklı bir yaşam tarzının temelidir. Egzersiz yapmak, fiziksel ve zihinsel sağlığı geliştirir, kilo kontrolüne yardımcı olur, stresi azaltır, enerji seviyelerini artırır ve kalp hastalığı, diyabet ve kanser gibi birçok kronik hastalığı önlemeye yardımcı olur.\r\n\r\nAyrıca, düzenli egzersiz yapmak, kas ve kemik sağlığını korumaya yardımcı olur, vücutta yağ oranını azaltır, kan dolaşımını artırır ve bağışıklık sistemini güçlendirir. Düzenli egzersiz yapmak aynı zamanda zihinsel sağlığı da etkiler ve stres ve kaygı gibi duygusal durumları kontrol altına almaya yardımcı olur.\r\n\r\nAncak, düzenli egzersiz yapmak için zaman ve motivasyon bulmak her zaman kolay değildir. Başlangıçta, yavaş ve istikrarlı bir programla başlamak ve egzersiz hedeflerini yavaş yavaş artırmak önemlidir. Ayrıca, egzersiz programını eğlenceli hale getirmek, bir egzersiz ortağı bulmak ve farklı egzersiz türlerini denemek, motivasyonu artırabilir.\r\n\r\nSonuç olarak, düzenli egzersiz yapmak, sağlıklı bir yaşam tarzının vazgeçilmez bir parçasıdır. Egzersiz programını kişiselleştirerek, hedeflerimize uygun bir şekilde tasarlamalıyız. Egzersiz yapmak zaman ve motivasyon gerektirse de, sağlığımız için yaptığımız en iyi yatırım olduğunu unutmamalıyız.",
                            CreatedByUsername = "editoruser",
                            CreatedDate = new DateTime(2023, 3, 17, 15, 41, 10, 17, DateTimeKind.Local).AddTicks(6600),
                            ImageUrl = "postImages/defaultImage.png",
                            IsActive = true,
                            IsDeleted = false,
                            LikeCount = 222,
                            Title = "Düzenli Egzersizin Önemi",
                            UpdatedByUsername = "editoruser",
                            UpdatedDate = new DateTime(2023, 3, 17, 15, 41, 10, 17, DateTimeKind.Local).AddTicks(6601),
                            UserId = 4,
                            ViewCount = 2324
                        },
                        new
                        {
                            Id = 9,
                            CommentCount = 0,
                            Content = "Dünya üzerindeki çevre sorunları giderek artıyor ve bu sorunların çözümü için sürdürülebilirlik kavramı hayati önem taşıyor. Sürdürülebilirlik, insanların ihtiyaçlarını karşılamak için doğal kaynakları kullanırken, gelecek nesillerin ihtiyaçlarını da göz önünde bulunduran bir yaklaşımı ifade eder.\r\n\r\nGünümüzde, iklim değişikliği, su kaynaklarının azalması, deniz kirliliği, ormansızlaşma, doğal habitatların yok olması ve atık yönetimi gibi birçok çevre sorunu var. Bu sorunların büyük bir kısmı, insan faaliyetlerinden kaynaklanmaktadır.\r\n\r\nSürdürülebilirlik, bu sorunları önlemek için birçok çözüm sunar. Örneğin, yenilenebilir enerji kaynaklarına yatırım yaparak, fosil yakıt tüketimini azaltabiliriz. Atık yönetimi programları oluşturarak, atık miktarını azaltabilir ve geri dönüşüm yaparak kaynakları yeniden kullanabiliriz. Sürdürülebilirlik aynı zamanda, tarım yöntemlerini değiştirerek, toprak erozyonunu önleyebilir ve su kaynaklarını daha etkin bir şekilde kullanabiliriz.\r\n\r\nSürdürülebilirlik, gelecek nesillerin ihtiyaçlarını da göz önünde bulundurduğu için, uzun vadeli bir yaklaşımı ifade eder. Bu nedenle, sürdürülebilirliğin önemi giderek artıyor. Herkesin bu konuda sorumluluk alması ve sürdürülebilir bir gelecek için çalışması gerekiyor.\r\n\r\nSonuç olarak, çevre sorunları ve sürdürülebilirlik, hayatımızın önemli bir parçasıdır. Sürdürülebilir bir gelecek için, herkesin sorumluluk alması ve doğal kaynakları verimli bir şekilde kullanması gerekiyor. Gelecek nesillerin de ihtiyaçlarını göz önünde bulundurarak, sürdürülebilir bir dünya için çalışmalıyız.",
                            CreatedByUsername = "editoruser",
                            CreatedDate = new DateTime(2023, 3, 17, 15, 41, 10, 17, DateTimeKind.Local).AddTicks(6607),
                            ImageUrl = "postImages/defaultImage.png",
                            IsActive = true,
                            IsDeleted = false,
                            LikeCount = 23,
                            Title = "Çevre Sorunları ve Sürdürülebilirlik",
                            UpdatedByUsername = "editoruser",
                            UpdatedDate = new DateTime(2023, 3, 17, 15, 41, 10, 17, DateTimeKind.Local).AddTicks(6608),
                            UserId = 4,
                            ViewCount = 223
                        },
                        new
                        {
                            Id = 10,
                            CommentCount = 0,
                            Content = "Dijital dönüşüm, işletmelerin dijital teknolojileri kullanarak iş süreçlerini yenilemesi ve iyileştirmesi anlamına gelir. Günümüzde işletmelerin büyük bir kısmı, dijital dönüşümü benimseyerek rekabet avantajı elde etmeye çalışıyor.\r\n\r\nDijital dönüşüm, işletmelerin müşteri deneyimini geliştirmesi, verimliliği artırması ve maliyetleri düşürmesi için birçok fırsat sunar. Örneğin, bulut tabanlı yazılımlar sayesinde işletmeler, verilerini güvenli bir şekilde depolayabilir ve erişebilir hale getirebilir. Bu da işletmelerin daha hızlı ve etkili kararlar almasına yardımcı olur.\r\n\r\nDijital dönüşüm aynı zamanda, işletmelerin müşterileriyle daha iyi etkileşim kurmasını sağlar. Örneğin, sosyal medya platformları sayesinde işletmeler, müşterileriyle daha kolay ve etkili bir şekilde iletişim kurabilir ve geri bildirimleri hızlı bir şekilde alabilir. Bu da müşteri deneyimini geliştirmeye yardımcı olur ve müşteri sadakatini artırır.\r\n\r\nDijital dönüşümün bir diğer avantajı da, işletmelerin daha verimli çalışmasını sağlamasıdır. Otomasyon teknolojileri sayesinde, işletmeler manuel işlemleri otomatikleştirebilir ve çalışanların zamanını daha verimli kullanabilir. Bu da işletmelerin maliyetleri düşürmesine ve üretkenliği artırmasına yardımcı olur.\r\n\r\nSonuç olarak, dijital dönüşüm işletmeler için önemli bir fırsat sunar. İşletmeler, dijital teknolojileri benimseyerek müşteri deneyimini geliştirebilir, verimliliği artırabilir ve maliyetleri düşürebilir. Dijital dönüşümü benimseyen işletmeler, rekabet avantajı elde edebilir ve başarıya daha kolay ulaşabilir.",
                            CreatedByUsername = "adminuser",
                            CreatedDate = new DateTime(2023, 3, 17, 15, 41, 10, 17, DateTimeKind.Local).AddTicks(6612),
                            ImageUrl = "postImages/defaultImage.png",
                            IsActive = true,
                            IsDeleted = false,
                            LikeCount = 1233,
                            Title = "Dijital Dönüşüm ve İşletmeler",
                            UpdatedByUsername = "adminuser",
                            UpdatedDate = new DateTime(2023, 3, 17, 15, 41, 10, 17, DateTimeKind.Local).AddTicks(6613),
                            UserId = 2,
                            ViewCount = 2223
                        },
                        new
                        {
                            Id = 11,
                            CommentCount = 0,
                            Content = "Yoga, bedenin fiziksel ve zihinsel sağlığı için birçok faydası olan bir uygulamadır. Yoga yapmak, insanların stresi azaltmasına, zihinsel sağlığı iyileştirmesine ve genel refahı arttırmasına yardımcı olur.\r\n\r\nYoga, vücuttaki kasları ve eklemleri güçlendirir, esnekliği arttırır ve duruşu düzeltir. Bu, aynı zamanda yaralanma riskini de azaltır. Ancak yoga sadece fiziksel sağlığa fayda sağlamaz, aynı zamanda zihinsel sağlığı da destekler.\r\n\r\nYoga yapmak, kişilerin zihinsel durumunu düzeltir ve stresi azaltır. Yoga uygulayıcıları, derin nefes alarak stresi azaltır ve zihinsel berraklığı arttırır. Bu da, zihinsel sağlığı iyileştirir ve depresyon, anksiyete ve diğer zihinsel sağlık sorunlarının semptomlarını hafifletir.\r\n\r\nYoga aynı zamanda, kişilerin farkındalığını arttırır ve meditatif bir etki yaratır. Bu, düşünceleri sakinleştirir ve kişilerin daha yüksek bir bilince ulaşmasına yardımcı olur. Yoga ayrıca, uyku kalitesini de arttırır ve yorgunluğu azaltır.\r\n\r\nSonuç olarak, yoga insanların hem fiziksel hem de zihinsel sağlıklarını iyileştirmelerine yardımcı olan bir uygulamadır. Yoga yapmak, stresi azaltır, zihinsel sağlığı iyileştirir, farkındalığı arttırır ve genel refahı arttırır. Yoga, sağlıklı bir yaşam tarzı için harika bir ek olarak da kullanılabilir.",
                            CreatedByUsername = "adminuser",
                            CreatedDate = new DateTime(2023, 3, 17, 15, 41, 10, 17, DateTimeKind.Local).AddTicks(6618),
                            ImageUrl = "postImages/defaultImage.png",
                            IsActive = true,
                            IsDeleted = false,
                            LikeCount = 211,
                            Title = "Yoga ve Zihinsel Sağlık",
                            UpdatedByUsername = "adminuser",
                            UpdatedDate = new DateTime(2023, 3, 17, 15, 41, 10, 17, DateTimeKind.Local).AddTicks(6619),
                            UserId = 2,
                            ViewCount = 2123
                        },
                        new
                        {
                            Id = 12,
                            CommentCount = 0,
                            Content = "Dijital yorgunluk, sürekli olarak dijital teknolojilerle etkileşim halinde olan insanların maruz kaldığı bir durumdur. Bu, sürekli olarak telefonlara, bilgisayarlara, tablet'lere ve diğer dijital cihazlara bakarak uzun saatler geçirerek gerçekleşir.\r\n\r\nDijital yorgunluk, yorgunluk, halsizlik, baş ağrısı, gözlerde yanma ve kuru his, boyun ağrısı, uykusuzluk, konsantrasyon güçlüğü ve hatta depresyon gibi çeşitli semptomlara neden olabilir. Bu semptomlar, dijital teknolojilere aşırı maruz kalmanın bir sonucudur.\r\n\r\nDijital yorgunluğu önlemek için, bazı öneriler şunlar olabilir:\r\n\r\nDijital cihaz kullanımını azaltın. Çok fazla zaman harcamaktan kaçının.\r\nTelefonunuza veya diğer cihazlarınıza bakmak yerine, gerçek hayattaki etkinliklere katılın.\r\nİnternet kullanımını sınırlandırın. Sosyal medya ve diğer dijital platformlarda harcadığınız süreyi azaltın.\r\nKendinize ara verin. Dijital cihazlarla aranızda zaman zaman uzaklaşın ve kendi kendinizle baş başa kalın.\r\nGözlerinizi dinlendirmek için her 20-30 dakikada bir göz egzersizleri yapın.\r\nSonuç olarak, dijital yorgunluk birçok kişi için yaygın bir sorundur. Bu semptomları önlemek için, dijital cihazların kullanımını sınırlandırmak ve kendi kendinizle zaman geçirmek önemlidir. Dijital yorgunluğun önlenmesi, daha sağlıklı bir yaşam tarzını sürdürmek için önemlidir.",
                            CreatedByUsername = "ozkky",
                            CreatedDate = new DateTime(2023, 3, 17, 15, 41, 10, 17, DateTimeKind.Local).AddTicks(6624),
                            ImageUrl = "postImages/defaultImage.png",
                            IsActive = true,
                            IsDeleted = false,
                            LikeCount = 233,
                            Title = "Dijital Yorgunluk: Belirtileri ve Nasıl Önlenir?",
                            UpdatedByUsername = "ozkky",
                            UpdatedDate = new DateTime(2023, 3, 17, 15, 41, 10, 17, DateTimeKind.Local).AddTicks(6625),
                            UserId = 1,
                            ViewCount = 2323
                        });
                });

            modelBuilder.Entity("BlogApp.Core.Entities.Concrete.BlogCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("BlogId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("BlogId", "CategoryId")
                        .IsUnique();

                    b.ToTable("BlogCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BlogId = 1,
                            CategoryId = 1
                        },
                        new
                        {
                            Id = 2,
                            BlogId = 1,
                            CategoryId = 5
                        },
                        new
                        {
                            Id = 3,
                            BlogId = 2,
                            CategoryId = 1
                        },
                        new
                        {
                            Id = 4,
                            BlogId = 3,
                            CategoryId = 4
                        },
                        new
                        {
                            Id = 5,
                            BlogId = 3,
                            CategoryId = 6
                        },
                        new
                        {
                            Id = 6,
                            BlogId = 3,
                            CategoryId = 9
                        },
                        new
                        {
                            Id = 7,
                            BlogId = 4,
                            CategoryId = 8
                        },
                        new
                        {
                            Id = 8,
                            BlogId = 5,
                            CategoryId = 4
                        },
                        new
                        {
                            Id = 9,
                            BlogId = 6,
                            CategoryId = 7
                        },
                        new
                        {
                            Id = 10,
                            BlogId = 6,
                            CategoryId = 10
                        },
                        new
                        {
                            Id = 11,
                            BlogId = 7,
                            CategoryId = 12
                        },
                        new
                        {
                            Id = 12,
                            BlogId = 8,
                            CategoryId = 13
                        },
                        new
                        {
                            Id = 13,
                            BlogId = 9,
                            CategoryId = 2
                        },
                        new
                        {
                            Id = 14,
                            BlogId = 9,
                            CategoryId = 3
                        },
                        new
                        {
                            Id = 15,
                            BlogId = 10,
                            CategoryId = 1
                        },
                        new
                        {
                            Id = 16,
                            BlogId = 10,
                            CategoryId = 9
                        },
                        new
                        {
                            Id = 17,
                            BlogId = 11,
                            CategoryId = 4
                        },
                        new
                        {
                            Id = 18,
                            BlogId = 11,
                            CategoryId = 5
                        },
                        new
                        {
                            Id = 19,
                            BlogId = 12,
                            CategoryId = 11
                        });
                });

            modelBuilder.Entity("BlogApp.Core.Entities.Concrete.BlogTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("BlogId")
                        .HasColumnType("int");

                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BlogId");

                    b.HasIndex("TagId", "BlogId");

                    b.ToTable("BlogTags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BlogId = 1,
                            TagId = 1
                        },
                        new
                        {
                            Id = 2,
                            BlogId = 1,
                            TagId = 2
                        },
                        new
                        {
                            Id = 3,
                            BlogId = 2,
                            TagId = 4
                        },
                        new
                        {
                            Id = 4,
                            BlogId = 2,
                            TagId = 6
                        },
                        new
                        {
                            Id = 5,
                            BlogId = 3,
                            TagId = 2
                        },
                        new
                        {
                            Id = 6,
                            BlogId = 3,
                            TagId = 3
                        },
                        new
                        {
                            Id = 7,
                            BlogId = 4,
                            TagId = 1
                        },
                        new
                        {
                            Id = 8,
                            BlogId = 4,
                            TagId = 9
                        },
                        new
                        {
                            Id = 9,
                            BlogId = 5,
                            TagId = 7
                        },
                        new
                        {
                            Id = 10,
                            BlogId = 5,
                            TagId = 10
                        },
                        new
                        {
                            Id = 11,
                            BlogId = 6,
                            TagId = 2
                        },
                        new
                        {
                            Id = 12,
                            BlogId = 7,
                            TagId = 3
                        },
                        new
                        {
                            Id = 13,
                            BlogId = 7,
                            TagId = 5
                        },
                        new
                        {
                            Id = 14,
                            BlogId = 8,
                            TagId = 4
                        },
                        new
                        {
                            Id = 15,
                            BlogId = 8,
                            TagId = 6
                        },
                        new
                        {
                            Id = 16,
                            BlogId = 9,
                            TagId = 7
                        },
                        new
                        {
                            Id = 17,
                            BlogId = 9,
                            TagId = 8
                        },
                        new
                        {
                            Id = 18,
                            BlogId = 10,
                            TagId = 9
                        },
                        new
                        {
                            Id = 19,
                            BlogId = 10,
                            TagId = 10
                        },
                        new
                        {
                            Id = 20,
                            BlogId = 11,
                            TagId = 2
                        },
                        new
                        {
                            Id = 21,
                            BlogId = 11,
                            TagId = 3
                        },
                        new
                        {
                            Id = 22,
                            BlogId = 12,
                            TagId = 3
                        },
                        new
                        {
                            Id = 23,
                            BlogId = 12,
                            TagId = 4
                        });
                });

            modelBuilder.Entity("BlogApp.Core.Entities.Concrete.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CreatedByUsername")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UpdatedByUsername")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedByUsername = "adminuser",
                            CreatedDate = new DateTime(2023, 3, 17, 15, 41, 10, 17, DateTimeKind.Local).AddTicks(6722),
                            Description = "Dünyadan teknoloji haberleri",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Teknoloji",
                            UpdatedByUsername = "adminuser",
                            UpdatedDate = new DateTime(2023, 3, 17, 15, 41, 10, 17, DateTimeKind.Local).AddTicks(6723)
                        },
                        new
                        {
                            Id = 2,
                            CreatedByUsername = "adminuser",
                            CreatedDate = new DateTime(2023, 3, 17, 15, 41, 10, 17, DateTimeKind.Local).AddTicks(6729),
                            Description = "Güncel yazılım gelişmeleri",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Yazılım",
                            UpdatedByUsername = "adminuser",
                            UpdatedDate = new DateTime(2023, 3, 17, 15, 41, 10, 17, DateTimeKind.Local).AddTicks(6730)
                        },
                        new
                        {
                            Id = 3,
                            CreatedByUsername = "adminuser",
                            CreatedDate = new DateTime(2023, 3, 17, 15, 41, 10, 17, DateTimeKind.Local).AddTicks(6734),
                            Description = "Dünyadan bilim haberleri",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Bilim",
                            UpdatedByUsername = "adminuser",
                            UpdatedDate = new DateTime(2023, 3, 17, 15, 41, 10, 17, DateTimeKind.Local).AddTicks(6736)
                        },
                        new
                        {
                            Id = 4,
                            CreatedByUsername = "adminuser",
                            CreatedDate = new DateTime(2023, 3, 17, 15, 41, 10, 17, DateTimeKind.Local).AddTicks(6740),
                            Description = "Eğitim hakkında en iyi bloglar",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Eğitim",
                            UpdatedByUsername = "adminuser",
                            UpdatedDate = new DateTime(2023, 3, 17, 15, 41, 10, 17, DateTimeKind.Local).AddTicks(6740)
                        },
                        new
                        {
                            Id = 5,
                            CreatedByUsername = "adminuser",
                            CreatedDate = new DateTime(2023, 3, 17, 15, 41, 10, 17, DateTimeKind.Local).AddTicks(6746),
                            Description = "Yerli ve yabancı otomobil haberleri",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Otomobil",
                            UpdatedByUsername = "adminuser",
                            UpdatedDate = new DateTime(2023, 3, 17, 15, 41, 10, 17, DateTimeKind.Local).AddTicks(6747)
                        },
                        new
                        {
                            Id = 6,
                            CreatedByUsername = "adminuser",
                            CreatedDate = new DateTime(2023, 3, 17, 15, 41, 10, 17, DateTimeKind.Local).AddTicks(6751),
                            Description = "Yerli ve yabancı oyun sektörü haberleri",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Oyun",
                            UpdatedByUsername = "adminuser",
                            UpdatedDate = new DateTime(2023, 3, 17, 15, 41, 10, 17, DateTimeKind.Local).AddTicks(6752)
                        },
                        new
                        {
                            Id = 7,
                            CreatedByUsername = "adminuser",
                            CreatedDate = new DateTime(2023, 3, 17, 15, 41, 10, 17, DateTimeKind.Local).AddTicks(6757),
                            Description = "Mühendislik alanlarındaki gelişmeler",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Mühendislik",
                            UpdatedByUsername = "adminuser",
                            UpdatedDate = new DateTime(2023, 3, 17, 15, 41, 10, 17, DateTimeKind.Local).AddTicks(6758)
                        },
                        new
                        {
                            Id = 8,
                            CreatedByUsername = "adminuser",
                            CreatedDate = new DateTime(2023, 3, 17, 15, 41, 10, 17, DateTimeKind.Local).AddTicks(6762),
                            Description = "Spor dünyasından haberler",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Spor",
                            UpdatedByUsername = "adminuser",
                            UpdatedDate = new DateTime(2023, 3, 17, 15, 41, 10, 17, DateTimeKind.Local).AddTicks(6763)
                        },
                        new
                        {
                            Id = 9,
                            CreatedByUsername = "adminuser",
                            CreatedDate = new DateTime(2023, 3, 17, 15, 41, 10, 17, DateTimeKind.Local).AddTicks(6767),
                            Description = "Kişisel gelişim hakkında en iyi bloglar",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Kişisel Gelişim",
                            UpdatedByUsername = "adminuser",
                            UpdatedDate = new DateTime(2023, 3, 17, 15, 41, 10, 17, DateTimeKind.Local).AddTicks(6768)
                        },
                        new
                        {
                            Id = 10,
                            CreatedByUsername = "adminuser",
                            CreatedDate = new DateTime(2023, 3, 17, 15, 41, 10, 17, DateTimeKind.Local).AddTicks(6772),
                            Description = "Sürdürülebilir yaşam",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Sürdürülebilir Yaşam",
                            UpdatedByUsername = "adminuser",
                            UpdatedDate = new DateTime(2023, 3, 17, 15, 41, 10, 17, DateTimeKind.Local).AddTicks(6773)
                        },
                        new
                        {
                            Id = 11,
                            CreatedByUsername = "adminuser",
                            CreatedDate = new DateTime(2023, 3, 17, 15, 41, 10, 17, DateTimeKind.Local).AddTicks(6778),
                            Description = "Dünyadan sağlıklı yaşam haberleri",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Sağlıklı Yaşam",
                            UpdatedByUsername = "adminuser",
                            UpdatedDate = new DateTime(2023, 3, 17, 15, 41, 10, 17, DateTimeKind.Local).AddTicks(6779)
                        },
                        new
                        {
                            Id = 12,
                            CreatedByUsername = "adminuser",
                            CreatedDate = new DateTime(2023, 3, 17, 15, 41, 10, 17, DateTimeKind.Local).AddTicks(6784),
                            Description = "Seyahat hakkında en iyi bloglar",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Seyahat",
                            UpdatedByUsername = "adminuser",
                            UpdatedDate = new DateTime(2023, 3, 17, 15, 41, 10, 17, DateTimeKind.Local).AddTicks(6785)
                        },
                        new
                        {
                            Id = 13,
                            CreatedByUsername = "adminuser",
                            CreatedDate = new DateTime(2023, 3, 17, 15, 41, 10, 17, DateTimeKind.Local).AddTicks(6790),
                            Description = "Kariyerinize yön verecek içerikler",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Kariyer",
                            UpdatedByUsername = "adminuser",
                            UpdatedDate = new DateTime(2023, 3, 17, 15, 41, 10, 17, DateTimeKind.Local).AddTicks(6791)
                        });
                });

            modelBuilder.Entity("BlogApp.Core.Entities.Concrete.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("BlogId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("CreatedByUsername")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Firstname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Lastname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedByUsername")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BlogId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BlogId = 1,
                            Content = "Teknoloji hayatımızın ayrılmaz bir parçası haline geldi. Gelişen teknoloji ile birlikte insan hayatı daha da kolaylaşıyor ve dijital dünya daha da genişliyor.",
                            CreatedByUsername = "memberuser",
                            CreatedDate = new DateTime(2023, 3, 17, 15, 41, 10, 17, DateTimeKind.Local).AddTicks(7186),
                            Email = "memberuser@gmail.com",
                            Firstname = "Member",
                            ImageUrl = "userImages/defaultUser.png",
                            IsActive = true,
                            IsDeleted = false,
                            Lastname = "Member",
                            UpdatedByUsername = "memberuser",
                            UpdatedDate = new DateTime(2023, 3, 17, 15, 41, 10, 17, DateTimeKind.Local).AddTicks(7187),
                            UserId = 3
                        },
                        new
                        {
                            Id = 2,
                            BlogId = 2,
                            Content = "Bilim, insanlık için son derece önemlidir. Bilim sayesinde dünya hakkında daha fazla şey öğreniyor ve hayatımızı daha iyi hale getiriyoruz. Bilimin gelişmesiyle birlikte, tıp, çevre, enerji ve diğer alanlarda önemli ilerlemeler kaydedildi.",
                            CreatedByUsername = "memberuser",
                            CreatedDate = new DateTime(2023, 3, 17, 15, 41, 10, 17, DateTimeKind.Local).AddTicks(7194),
                            Email = "memberuser@gmail.com",
                            Firstname = "Member",
                            ImageUrl = "userImages/defaultUser.png",
                            IsActive = true,
                            IsDeleted = false,
                            Lastname = "Member",
                            UpdatedByUsername = "memberuser",
                            UpdatedDate = new DateTime(2023, 3, 17, 15, 41, 10, 17, DateTimeKind.Local).AddTicks(7195),
                            UserId = 3
                        },
                        new
                        {
                            Id = 3,
                            BlogId = 3,
                            Content = "Sanat, insanlığın ruhunu besleyen bir kaynaktır. Sanat, farklı kültürler ve farklı dönemlerden gelen insanların duygularını, hayallerini ve düşüncelerini yansıtır.",
                            CreatedByUsername = "editoruser",
                            CreatedDate = new DateTime(2023, 3, 17, 15, 41, 10, 17, DateTimeKind.Local).AddTicks(7200),
                            Email = "editoruser@gmail.com",
                            Firstname = "Editor",
                            ImageUrl = "userImages/defaultUser.png",
                            IsActive = true,
                            IsDeleted = false,
                            Lastname = "Editor",
                            UpdatedByUsername = "editoruser",
                            UpdatedDate = new DateTime(2023, 3, 17, 15, 41, 10, 17, DateTimeKind.Local).AddTicks(7201),
                            UserId = 4
                        },
                        new
                        {
                            Id = 4,
                            BlogId = 4,
                            Content = "Otomobil, modern yaşamın önemli bir parçasıdır. Otomobiller, günlük hayatımızda işe, okula veya seyahat etmek için kullandığımız en yaygın taşıtlardan biridir. Ancak, otomobillerin çevresel etkileri de düşünülmesi gereken önemli bir konudur.",
                            CreatedByUsername = "editoruser",
                            CreatedDate = new DateTime(2023, 3, 17, 15, 41, 10, 17, DateTimeKind.Local).AddTicks(7206),
                            Email = "editoruser@gmail.com",
                            Firstname = "Editor",
                            ImageUrl = "userImages/defaultUser.png",
                            IsActive = true,
                            IsDeleted = false,
                            Lastname = "Editor",
                            UpdatedByUsername = "editoruser",
                            UpdatedDate = new DateTime(2023, 3, 17, 15, 41, 10, 17, DateTimeKind.Local).AddTicks(7207),
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            BlogId = 5,
                            Content = "Sağlıklı yaşam, insan hayatı için son derece önemlidir. Sağlıklı beslenme, düzenli egzersiz ve uyku, stres yönetimi gibi faktörler, sağlıklı yaşam için önemlidir. Sağlıklı yaşam, uzun ve mutlu bir hayat için temel gereksinimdir.",
                            CreatedByUsername = "adminuser",
                            CreatedDate = new DateTime(2023, 3, 17, 15, 41, 10, 17, DateTimeKind.Local).AddTicks(7213),
                            Email = "adminuser@gmail.com",
                            Firstname = "Admin",
                            ImageUrl = "userImages/defaultUser.png",
                            IsActive = true,
                            IsDeleted = false,
                            Lastname = "Admin",
                            UpdatedByUsername = "adminuser",
                            UpdatedDate = new DateTime(2023, 3, 17, 15, 41, 10, 17, DateTimeKind.Local).AddTicks(7214),
                            UserId = 2
                        },
                        new
                        {
                            Id = 6,
                            BlogId = 5,
                            Content = "Eğitim, toplumun gelişmesi için en önemli araçlardan biridir. Eğitim sayesinde insanlar, dünya hakkında daha fazla şey öğrenirler ve kendilerini geliştirirler. Eğitim, insan hayatında bir dönüm noktasıdır ve hayatımız boyunca öğrenmeye devam etmek önemlidir.",
                            CreatedByUsername = "adminuser",
                            CreatedDate = new DateTime(2023, 3, 17, 15, 41, 10, 17, DateTimeKind.Local).AddTicks(7219),
                            Email = "adminuser@gmail.com",
                            Firstname = "Admin",
                            ImageUrl = "userImages/defaultUser.png",
                            IsActive = true,
                            IsDeleted = false,
                            Lastname = "Admin",
                            UpdatedByUsername = "adminuser",
                            UpdatedDate = new DateTime(2023, 3, 17, 15, 41, 10, 17, DateTimeKind.Local).AddTicks(7220),
                            UserId = 2
                        },
                        new
                        {
                            Id = 7,
                            BlogId = 4,
                            Content = "Kariyer, iş hayatında başarıya ulaşmak için önemlidir. İyi bir kariyer yapmak, finansal bağımsızlık ve kişisel tatmin açısından önemlidir. Ancak, kariyer hedefleri belirlerken, kişinin yeteneklerini ve değerlerini dikkate alması gereklidir.",
                            CreatedByUsername = "editoruser",
                            CreatedDate = new DateTime(2023, 3, 17, 15, 41, 10, 17, DateTimeKind.Local).AddTicks(7226),
                            Email = "editoruser@gmail.com",
                            Firstname = "Editor",
                            ImageUrl = "userImages/defaultUser.png",
                            IsActive = true,
                            IsDeleted = false,
                            Lastname = "Editor",
                            UpdatedByUsername = "editoruser",
                            UpdatedDate = new DateTime(2023, 3, 17, 15, 41, 10, 17, DateTimeKind.Local).AddTicks(7227),
                            UserId = 4
                        },
                        new
                        {
                            Id = 8,
                            BlogId = 5,
                            Content = "Seyahat, yeni yerler keşfetmek, farklı kültürleri tanımak ve yeni deneyimler edinmek için harika bir yoldur. Seyahat etmek, kişinin bakış açısını genişletir ve yaşam deneyimini zenginleştirir. Ancak, seyahat ederken, diğer kültürlerin saygı göstermek ve doğal kaynaklara zarar vermemek gibi sorumlulukları da unutmamak gereklidir.",
                            CreatedByUsername = "adminuser",
                            CreatedDate = new DateTime(2023, 3, 17, 15, 41, 10, 17, DateTimeKind.Local).AddTicks(7232),
                            Email = "adminuser@gmail.com",
                            Firstname = "Admin",
                            ImageUrl = "userImages/defaultUser.png",
                            IsActive = true,
                            IsDeleted = false,
                            Lastname = "Admin",
                            UpdatedByUsername = "adminuser",
                            UpdatedDate = new DateTime(2023, 3, 17, 15, 41, 10, 17, DateTimeKind.Local).AddTicks(7233),
                            UserId = 2
                        },
                        new
                        {
                            Id = 9,
                            BlogId = 6,
                            Content = "Eğitimde yeni metotlar, öğrenme teknikleri, öğrenci motivasyonu ve sınavlara hazırlık gibi konular hakkında paylaşılan bilgiler, öğrencilerin başarılarını arttırabilir.",
                            CreatedByUsername = "memberuser",
                            CreatedDate = new DateTime(2023, 3, 17, 15, 41, 10, 17, DateTimeKind.Local).AddTicks(7239),
                            Email = "memberuser@gmail.com",
                            Firstname = "Member",
                            ImageUrl = "userImages/defaultUser.png",
                            IsActive = true,
                            IsDeleted = false,
                            Lastname = "Member",
                            UpdatedByUsername = "memberuser",
                            UpdatedDate = new DateTime(2023, 3, 17, 15, 41, 10, 17, DateTimeKind.Local).AddTicks(7240),
                            UserId = 3
                        },
                        new
                        {
                            Id = 10,
                            BlogId = 7,
                            Content = "Yeni kültürler keşfetmek, farklı yemekleri tatmak, yeni insanlarla tanışmak gibi seyahat etmenin birçok faydası var. Bu başlık altında yer alan yazılar, insanların seyahatlerini planlamalarına ve daha keyifli bir deneyim yaşamalarına yardımcı olabilir.",
                            CreatedByUsername = "superadminuser",
                            CreatedDate = new DateTime(2023, 3, 17, 15, 41, 10, 17, DateTimeKind.Local).AddTicks(7245),
                            Email = "ozkky@gmail.com",
                            Firstname = "Özkan",
                            ImageUrl = "userImages/defaultUser.png",
                            IsActive = true,
                            IsDeleted = false,
                            Lastname = "Akkaya",
                            UpdatedByUsername = "superadminuser",
                            UpdatedDate = new DateTime(2023, 3, 17, 15, 41, 10, 17, DateTimeKind.Local).AddTicks(7246),
                            UserId = 1
                        });
                });

            modelBuilder.Entity("BlogApp.Core.Entities.Concrete.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Contact");
                });

            modelBuilder.Entity("BlogApp.Core.Entities.Concrete.Gender", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Definition")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Genders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Definition = "Man"
                        },
                        new
                        {
                            Id = 2,
                            Definition = "Woman"
                        },
                        new
                        {
                            Id = 3,
                            Definition = "Undefined"
                        });
                });

            modelBuilder.Entity("BlogApp.Core.Entities.Concrete.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Category.Create"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Category.Read"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Category.Update"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Category.Delete"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Blog.Create"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Blog.Read"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Blog.Update"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Blog.Delete"
                        },
                        new
                        {
                            Id = 9,
                            Name = "User.Create"
                        },
                        new
                        {
                            Id = 10,
                            Name = "User.Read"
                        },
                        new
                        {
                            Id = 11,
                            Name = "User.Update"
                        },
                        new
                        {
                            Id = 12,
                            Name = "User.Delete"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Role.Create"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Role.Read"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Role.Update"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Role.Delete"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Comment.Create"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Comment.Read"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Comment.Update"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Comment.Delete"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Member"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 23,
                            Name = "SuperAdmin"
                        });
                });

            modelBuilder.Entity("BlogApp.Core.Entities.Concrete.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CreatedByUsername")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("UpdatedByUsername")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedByUsername = "adminuser",
                            CreatedDate = new DateTime(2023, 3, 17, 15, 41, 10, 17, DateTimeKind.Local).AddTicks(7301),
                            Description = "Son teknoloji haberleri ve yenilikler",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Teknoloji",
                            UpdatedByUsername = "adminuser",
                            UpdatedDate = new DateTime(2023, 3, 17, 15, 41, 10, 17, DateTimeKind.Local).AddTicks(7303)
                        },
                        new
                        {
                            Id = 2,
                            CreatedByUsername = "adminuser",
                            CreatedDate = new DateTime(2023, 3, 17, 15, 41, 10, 17, DateTimeKind.Local).AddTicks(7309),
                            Description = "En son bilim keşifleri ve araştırmaları",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Bilim Keşifleri",
                            UpdatedByUsername = "adminuser",
                            UpdatedDate = new DateTime(2023, 3, 17, 15, 41, 10, 17, DateTimeKind.Local).AddTicks(7310)
                        },
                        new
                        {
                            Id = 3,
                            CreatedByUsername = "adminuser",
                            CreatedDate = new DateTime(2023, 3, 17, 15, 41, 10, 17, DateTimeKind.Local).AddTicks(7315),
                            Description = "Sanat dünyasındaki son gelişmeler ve haberler",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Sanat Dünyası",
                            UpdatedByUsername = "adminuser",
                            UpdatedDate = new DateTime(2023, 3, 17, 15, 41, 10, 17, DateTimeKind.Local).AddTicks(7316)
                        },
                        new
                        {
                            Id = 4,
                            CreatedByUsername = "adminuser",
                            CreatedDate = new DateTime(2023, 3, 17, 15, 41, 10, 17, DateTimeKind.Local).AddTicks(7322),
                            Description = "En son otomobil haberleri ve yenilikler",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Otomobil",
                            UpdatedByUsername = "adminuser",
                            UpdatedDate = new DateTime(2023, 3, 17, 15, 41, 10, 17, DateTimeKind.Local).AddTicks(7323)
                        },
                        new
                        {
                            Id = 5,
                            CreatedByUsername = "adminuser",
                            CreatedDate = new DateTime(2023, 3, 17, 15, 41, 10, 17, DateTimeKind.Local).AddTicks(7328),
                            Description = "Sağlıklı yaşam, beslenme ve egzersiz tavsiyeleri",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Sağlıklı Yaşam",
                            UpdatedByUsername = "adminuser",
                            UpdatedDate = new DateTime(2023, 3, 17, 15, 41, 10, 17, DateTimeKind.Local).AddTicks(7328)
                        },
                        new
                        {
                            Id = 6,
                            CreatedByUsername = "adminuser",
                            CreatedDate = new DateTime(2023, 3, 17, 15, 41, 10, 17, DateTimeKind.Local).AddTicks(7333),
                            Description = "Eğitim dünyasındaki son gelişmeler ve haberler",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Eğitim Gündemi",
                            UpdatedByUsername = "adminuser",
                            UpdatedDate = new DateTime(2023, 3, 17, 15, 41, 10, 17, DateTimeKind.Local).AddTicks(7334)
                        },
                        new
                        {
                            Id = 7,
                            CreatedByUsername = "adminuser",
                            CreatedDate = new DateTime(2023, 3, 17, 15, 41, 10, 17, DateTimeKind.Local).AddTicks(7338),
                            Description = "Kariyer yolculuğunuza rehberlik edecek tavsiyeler",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Kariyer",
                            UpdatedByUsername = "adminuser",
                            UpdatedDate = new DateTime(2023, 3, 17, 15, 41, 10, 17, DateTimeKind.Local).AddTicks(7339)
                        },
                        new
                        {
                            Id = 8,
                            CreatedByUsername = "adminuser",
                            CreatedDate = new DateTime(2023, 3, 17, 15, 41, 10, 17, DateTimeKind.Local).AddTicks(7343),
                            Description = "Keşfedilmesi gereken seyahat rotaları ve öneriler",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Seyahat",
                            UpdatedByUsername = "adminuser",
                            UpdatedDate = new DateTime(2023, 3, 17, 15, 41, 10, 17, DateTimeKind.Local).AddTicks(7344)
                        },
                        new
                        {
                            Id = 9,
                            CreatedByUsername = "adminuser",
                            CreatedDate = new DateTime(2023, 3, 17, 15, 41, 10, 17, DateTimeKind.Local).AddTicks(7349),
                            Description = "Eğlendirirken bilgilendiren içerikler",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Bilgi Dolu Eğlence",
                            UpdatedByUsername = "adminuser",
                            UpdatedDate = new DateTime(2023, 3, 17, 15, 41, 10, 17, DateTimeKind.Local).AddTicks(7350)
                        },
                        new
                        {
                            Id = 10,
                            CreatedByUsername = "adminuser",
                            CreatedDate = new DateTime(2023, 3, 17, 15, 41, 10, 17, DateTimeKind.Local).AddTicks(7354),
                            Description = "Yazılım hakkında içerikler",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Yazılım",
                            UpdatedByUsername = "adminuser",
                            UpdatedDate = new DateTime(2023, 3, 17, 15, 41, 10, 17, DateTimeKind.Local).AddTicks(7355)
                        });
                });

            modelBuilder.Entity("BlogApp.Core.Entities.Concrete.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("About")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("CreatedByUsername")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("GenderId")
                        .HasColumnType("int");

                    b.Property<string>("GitHubLink")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("UpdatedByUsername")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("WebsiteLink")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("GenderId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            About = "Blog sitesinin süper admini",
                            CreatedByUsername = "ozkky",
                            CreatedDate = new DateTime(2023, 3, 17, 15, 41, 9, 94, DateTimeKind.Local).AddTicks(5827),
                            Email = "ozkky@gmail.com",
                            Firstname = "Özkan",
                            GenderId = 1,
                            GitHubLink = "ozkanakkaya",
                            ImageUrl = "userImages/defaultUser.png",
                            IsActive = true,
                            IsDeleted = false,
                            Lastname = "Akkaya",
                            PasswordHash = "AQAAAAIAAYagAAAAECMT+LfFaspuqH3rPFcY1cdJNl9KDnNIAUyA8PRj285xzgTTII9KTJ9We6gArcsjCg==",
                            PhoneNumber = "5555555555",
                            UpdatedByUsername = "ozkky",
                            UpdatedDate = new DateTime(2023, 3, 17, 15, 41, 9, 94, DateTimeKind.Local).AddTicks(5829),
                            Username = "ozkky",
                            WebsiteLink = "ozkanakkaya.com"
                        },
                        new
                        {
                            Id = 2,
                            About = "Blog sitesinin admini",
                            CreatedByUsername = "adminuser",
                            CreatedDate = new DateTime(2023, 3, 17, 15, 41, 9, 316, DateTimeKind.Local).AddTicks(1181),
                            Email = "adminuser@gmail.com",
                            Firstname = "Admin",
                            GenderId = 2,
                            GitHubLink = "adminuser",
                            ImageUrl = "userImages/defaultUser.png",
                            IsActive = true,
                            IsDeleted = false,
                            Lastname = "Admin",
                            PasswordHash = "AQAAAAIAAYagAAAAEGwQEUuOvHt1f6fni8zjLcXIpw/+zhM676D5jc6Icq7JYVeohcJgJ3Fdnv+P8S7pCQ==",
                            PhoneNumber = "5555555555",
                            UpdatedByUsername = "adminuser",
                            UpdatedDate = new DateTime(2023, 3, 17, 15, 41, 9, 316, DateTimeKind.Local).AddTicks(1183),
                            Username = "adminuser",
                            WebsiteLink = "adminuser.com"
                        },
                        new
                        {
                            Id = 3,
                            About = "Blog sitesinde üye kullanıcı",
                            CreatedByUsername = "editoruser",
                            CreatedDate = new DateTime(2023, 3, 17, 15, 41, 9, 574, DateTimeKind.Local).AddTicks(539),
                            Email = "memberuser@gmail.com",
                            Firstname = "Member",
                            GenderId = 1,
                            GitHubLink = "memberuser",
                            ImageUrl = "userImages/defaultUser.png",
                            IsActive = true,
                            IsDeleted = false,
                            Lastname = "Member",
                            PasswordHash = "AQAAAAIAAYagAAAAENqVZfuCj1lTdGD70L7sv5cmPyG65iq4mZKOlHAarOccsBX4bhpkpT2jwFUxDA0wng==",
                            PhoneNumber = "5555555555",
                            UpdatedByUsername = "editoruser",
                            UpdatedDate = new DateTime(2023, 3, 17, 15, 41, 9, 574, DateTimeKind.Local).AddTicks(541),
                            Username = "memberuser",
                            WebsiteLink = "memberuser.com"
                        },
                        new
                        {
                            Id = 4,
                            About = "Blog sitesinde üye editör",
                            CreatedByUsername = "editoruser",
                            CreatedDate = new DateTime(2023, 3, 17, 15, 41, 9, 768, DateTimeKind.Local).AddTicks(4974),
                            Email = "editoruser@gmail.com",
                            Firstname = "Editor",
                            GenderId = 1,
                            GitHubLink = "editoruser",
                            ImageUrl = "userImages/defaultUser.png",
                            IsActive = true,
                            IsDeleted = false,
                            Lastname = "Editor",
                            PasswordHash = "AQAAAAIAAYagAAAAEJqEXWKJMh/sr3WEgXNaqUZrkqCJL/PzOhggckw9c+NiZNQAjhF8Ap0UafM5stTqGA==",
                            PhoneNumber = "5555555555",
                            UpdatedByUsername = "editoruser",
                            UpdatedDate = new DateTime(2023, 3, 17, 15, 41, 9, 768, DateTimeKind.Local).AddTicks(4976),
                            Username = "editoruser",
                            WebsiteLink = "editoruser.com"
                        });
                });

            modelBuilder.Entity("BlogApp.Core.Entities.Concrete.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("RoleId", "UserId")
                        .IsUnique();

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RoleId = 23,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            RoleId = 22,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            RoleId = 21,
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            RoleId = 6,
                            UserId = 3
                        },
                        new
                        {
                            Id = 5,
                            RoleId = 17,
                            UserId = 3
                        },
                        new
                        {
                            Id = 6,
                            RoleId = 21,
                            UserId = 4
                        },
                        new
                        {
                            Id = 7,
                            RoleId = 6,
                            UserId = 4
                        },
                        new
                        {
                            Id = 8,
                            RoleId = 7,
                            UserId = 4
                        },
                        new
                        {
                            Id = 9,
                            RoleId = 17,
                            UserId = 4
                        });
                });

            modelBuilder.Entity("BlogApp.Core.Entities.Concrete.Blog", b =>
                {
                    b.HasOne("BlogApp.Core.Entities.Concrete.User", "User")
                        .WithMany("Blogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BlogApp.Core.Entities.Concrete.BlogCategory", b =>
                {
                    b.HasOne("BlogApp.Core.Entities.Concrete.Blog", "Blog")
                        .WithMany("BlogCategories")
                        .HasForeignKey("BlogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlogApp.Core.Entities.Concrete.Category", "Category")
                        .WithMany("BlogCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Blog");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("BlogApp.Core.Entities.Concrete.BlogTag", b =>
                {
                    b.HasOne("BlogApp.Core.Entities.Concrete.Blog", "Blog")
                        .WithMany("BlogTags")
                        .HasForeignKey("BlogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlogApp.Core.Entities.Concrete.Tag", "Tag")
                        .WithMany("BlogTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Blog");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("BlogApp.Core.Entities.Concrete.Comment", b =>
                {
                    b.HasOne("BlogApp.Core.Entities.Concrete.Blog", "Blog")
                        .WithMany("Comments")
                        .HasForeignKey("BlogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Blog");
                });

            modelBuilder.Entity("BlogApp.Core.Entities.Concrete.User", b =>
                {
                    b.HasOne("BlogApp.Core.Entities.Concrete.Gender", "Gender")
                        .WithMany("Users")
                        .HasForeignKey("GenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gender");
                });

            modelBuilder.Entity("BlogApp.Core.Entities.Concrete.UserRole", b =>
                {
                    b.HasOne("BlogApp.Core.Entities.Concrete.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlogApp.Core.Entities.Concrete.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BlogApp.Core.Entities.Concrete.Blog", b =>
                {
                    b.Navigation("BlogCategories");

                    b.Navigation("BlogTags");

                    b.Navigation("Comments");
                });

            modelBuilder.Entity("BlogApp.Core.Entities.Concrete.Category", b =>
                {
                    b.Navigation("BlogCategories");
                });

            modelBuilder.Entity("BlogApp.Core.Entities.Concrete.Gender", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("BlogApp.Core.Entities.Concrete.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("BlogApp.Core.Entities.Concrete.Tag", b =>
                {
                    b.Navigation("BlogTags");
                });

            modelBuilder.Entity("BlogApp.Core.Entities.Concrete.User", b =>
                {
                    b.Navigation("Blogs");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
